services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    image: wordpress
    env_file:
      - .env
    secrets:
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_user_password
      - wp_user_email
      - db_password
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

networks:
   inception:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jolivare/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jolivare/data/wordpress_data
      o: bind

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_user_email:
    file: ../secrets/wp_user_email.txt